lst = ["bannana" , "apple" , "guava" , "mango", "pineapple"]
print ("length of lst", len(lst))
print ("first element", lst[0])
print ("last element", lst[4])
lst.append("grapes")
print(lst)
lst.remove("guava")
print(lst)
lst.pop(1)
print(lst)
lst.sort()
print(lst)
lst.reverse()
print(lst)
lst = lst[1:3]
print(lst)
print(lst*2)
lst.clear()
print(lst)